### ISSUE TITLE
restore_original_xml doesn't exist

### ISSUE THREAD

**Issue by emontgomery-usgs** [esturdivant-usgs/science-base-automation#38]
@esturdivant-usgs I think this is an easy fix-
![image](https://user-images.githubusercontent.com/1771422/36317795-11487302-130c-11e8-9def-b9f5e8c14313.png)

**Comment by esturdivant-usgs** [comment]
@emontgomery-usgs Are you using the same config_autoSB.py file? I added a parameter: 'restore_original_xml' in the new version.

**Comment by emontgomery-usgs** [comment]
I wrote over the new one with the old.  Sorry!
