### ISSUE TITLE
citation of child is sometimes wrong

### ISSUE THREAD

**Issue by afarrisusgs** [esturdivant-usgs/science-base-automation#44]
In this directory structure:
Child: BuzzardsBay
Contour is a child under BuzzardsBay
Profile is another child under BuzzardsBay

The citation for the data in the "Profile" child, is the same as the citation for the 'Contour' child.

**Comment by esturdivant-usgs** [comment]
Is this about the Citation displayed under the title on the page themselves? Such as in this screenshot: 

![image](https://user-images.githubusercontent.com/22688320/47731338-447c2280-dc3a-11e8-8890-bb5459543d7d.png)

If so, then that is inherited from the top landing page, which is a-okay. You want the citation on every page to be identical, as I understand it.

**Comment by afarrisusgs** [comment]
I thought Emily wanted then all different, but I think you are right.  I think the citation on the main page is somehow the contour citation.  Ugh.  Let me look at it more.

**Comment by afarrisusgs** [comment]
You were right!!!  The citation on the first page was a contour citation and it was population all the children.  Sorry!!!  
There is nothing wrong with the python code!

**Comment by esturdivant-usgs** [comment]
Great!! Thanks for using the issue section :)
