### ISSUE TITLE
Odd text found in XML files after processing 

### ISSUE THREAD

**Issue by afarrisusgs** [esturdivant-usgs/science-base-automation#45]
this block

    <ptvctinf>
      <sdtsterm>
        <sdtstype>String</sdtstype>
        <ptvctcnt>1089</ptvctcnt>
      </sdtsterm>
    </ptvctinf>
  </spdoinfo>

was deleted and this block was added
				<attalias Sync="TRUE">FID</attalias><attrtype Sync="TRUE">OID</attrtype><attwidth Sync="TRUE">4</attwidth><atprecis Sync="TRUE">0</atprecis><attscale Sync="TRUE">0</attscale></attr>

In fact, that bit of stuff was added all over the place.

**Comment by esturdivant-usgs** [comment]
Reported in two other issues by the same user: #46 #42

**Comment by esturdivant-usgs** [comment]
I've never seen this happen. If it happens while I'm processing or if there's an update to this, I'll follow up.
