### ISSUE TITLE
detailed changed

### ISSUE THREAD

**Issue by afarrisusgs** [esturdivant-usgs/science-base-automation#46]
this bit

> 

  <detailed>
   <enttyp>
    <enttypl>MAcontourShoreline_2012_14</enttypl>
    <enttypd>contour-derived mean high water shoreline for Massachusetts coast used in shoreline change analysis.</enttypd>
  <enttypds>U.S. Geological Survey</enttypds>
   </enttyp> 

> 

was changed to this bit:
	<detailed Name="MAcontourShoreline_2012_2014">
			<enttyp>
				<enttypl>MAcontourShoreline_2012_14</enttypl>
				<enttypd>contour-derived mean high water shoreline for Massachusetts coast used in shoreline change analysis.</enttypd>
				<enttypds>U.S. Geological Survey</enttypds>
				<enttypt Sync="TRUE">Feature Class</enttypt><enttypc Sync="TRUE">1064</enttypc></enttyp>

**Comment by esturdivant-usgs** [comment]
Will address this in issue #45
